name: Deploy to InfinityFree

on:
  push:
    branches:
      - main  # Cambia esto por la rama que uses para desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FTP Client
      run: sudo apt-get install -y lftp

    - name: Deploy to FTP
      env:
        FTP_HOST: 185.27.134.11  # Cambia esto por el host FTP de InfinityFree
        FTP_USER: if0_37597323    # Cambia esto por tu nombre de usuario de FTP
        FTP_PASS: qY6Z4UmFnp8uB    # Cambia esto por tu contrase√±a de FTP
      run: |
        lftp -f "
        open \$FTP_HOST
        user \$FTP_USER \$FTP_PASS
        mirror -R ./ htdocs/ --delete
        bye
        "
